ai_content_generator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('content/', include('content.urls', namespace='content')),
    path('chat/', include('drm_chat.urls')),
    path('chatbot/', include('chatbot.urls')),
    path('stackflow/', include('questionflow.urls', namespace='questionflow')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
     path("__reload__/", include("django_browser_reload.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('task_list/', views.todo_list, name="todo_list"),
    path('submit-task/', views.submit_task, name="submit-task"),
    path('complete-task/<str:pk>/', views.complete_task, name="complete-task"),
    path('delete-task/<str:pk>/', views.delete_task, name="delete-task"),
    path('profile/<username>/', views.profile, name="profile_detail"),
    path('profile/', views.profile, name="profile"),
    path('profile_edit/', views.profile_edit_view, name="profile_edit"),
    # path('follow/<int:user_id>/', views.follow_user, name='follow_user'),
    # path('unfollow/<int:user_id>/', views.unfollow_user, name='unfollow_user'),
]

questionflow/urls.py
from django.urls import path
from . import views

app_name='questionflow'
urlpatterns = [
    path('', views.question_list, name='questions'),
    path('recent-questions/', views.recent_questions, name='recent_question'),
    path('<tag>/', views.question_list, name='tagger'),
    path('question-create/', views.question_create, name='question-create'),
    path('question-detail/<str:pk>/', views.question_detail, name='question-detail'),
    path('upvote-question/<str:pk>/', views.upvote_question, name='upvote_question')
]

core/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django_resized import ResizedImageField
import os
from django.conf import settings
import uuid
from django_countries.fields import CountryField
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    addressLine1 = models.CharField(max_length=100, null=True, blank=True)
    addressLine2 = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    country = CountryField(blank_label='(Select country)', max_length=100, null=True, blank=True)
    postalCode = models.CharField(max_length=100, null=True, blank=True)
    profileImage = ResizedImageField(size=[200, 200], quality=90, upload_to='profile_images', null=True, blank=True)
    #   utility variable
    uniqueId = models.CharField(max_length=100, unique=True, default=uuid.uuid4, blank=True, null=True, editable=False)
    slug = models.SlugField(null=True, blank=True, max_length=500)
    date_created = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f'Profile {self.user.username}'

    def get_absolute_url(self):
        return reverse('profile-detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if self.date_created is None:
             self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid()).split('-')[4]
        
        self.slug = slugify('{}'.format(self.user.username))
        self.last_updated = timezone.localtime(timezone.now())
        super(Profile, self).save(*args, **kwargs)

    @property
    def get_profile_image(self):
        if self.profileImage:
            return self.profileImage.url
        else:
            return settings.MEDIA_URL + 'image/icons/user.png'


class Task(models.Model):
    TASK_CATEGORY = (
        ('Work', 'Work'),
        ('Personal', 'Personal'),
        ('Other', 'Other')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    category = models.CharField(max_length=100, choices=TASK_CATEGORY)
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']


    def __str__(self):
        return self.title


# class Follow(models.Model):
#     follower = models.ForeignKey(User, related_name='following', on_delete=models.CASCADE)
#     following = models.ForeignKey(User, related_name='followers', on_delete=models.CASCADE)
#     created_at = models.DateTimeField(auto_now_add=True)

core/forms.py
from django import forms
from .models import *
from django_countries.fields import CountryField

class ProfileForm(forms.ModelForm):
    country = CountryField(blank_label='(Select country)', max_length=100).formfield(
        widget=forms.Select(attrs={
            'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
        })
    )
    class Meta:
        model = Profile
        fields = [
            'addressLine1',
            'addressLine2',
            'city',
            'country',
            'postalCode',
            ]


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'category']

core/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from .forms import ProfileForm, TaskForm
from django.contrib.auth.decorators import login_required
from .models import *
from django.views.decorators.http import require_POST, require_http_methods
from django.http import HttpResponse
from .filters import TaskFilter
from django.contrib.auth.models import User
from questionflow.models import *

# Create your views here.

def home(request):
    return render(request, 'core/landing.html')

@login_required
def dashboard(request):
    questions = Question.objects.filter(user=request.user).count
    task = Task.objects.filter(user=request.user).count
    users = User.objects.exclude(id=request.user.id)
    # answers = Answer.objects.filter()
    context = {
        'users':users,
        'question_count':questions,
        # 'answer_count':An,
        'task_count':task
    }
    return render(request, 'core/dashboard.html', context)


# profile view actions page
@login_required
def profile_edit_view(request):
    if not request.user.is_authenticated:
        return redirect('login')
    form = ProfileForm(instance=request.user.profile)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('profile', request.user.username)
    else:
        form = ProfileForm(instance=request.user.profile)
    context = {
        'form': form
    }
    return render(request, 'core/profile_edit.html')
@login_required
def profile(request, username=None):
    if username:
        profile = get_object_or_404(User, username=username).profile
    else:
        profile = request.user.profile

    context ={
        'profile':profile
    }
    return render(request, 'core/profile.html', context)


#todo list view actions page

@login_required
def todo_list(request):
    task_filter = TaskFilter(request.GET, queryset=Task.objects.filter(user=request.user).order_by('-created_at'))


    form = TaskForm()
    context = {
        'filter':task_filter,
        'form':form,
    }
    if request.htmx:
        return render(request, 'core/partials/tasks.html', context)
    return render(request, 'core/todo_list.html', context)


@login_required
@require_POST
def submit_task(request):
    form = TaskForm(request.POST)
    if form.is_valid():
        task = form.save(commit=False)
        task.user = request.user
        task.save()
        #return an Html partial
        context = {'task':task}
        return render(request,'core/todo_list.html#taskitem-partial', context)
    
@login_required
@require_POST
def complete_task(request, pk):
    task = get_object_or_404(Task, pk=pk, user=request.user)
    task.is_completed = True
    task.save()
    context = {'task':task}
    return render(request,'core/todo_list.html#taskcomplete-partial', context)


@login_required
@require_http_methods(['DELETE'])
def delete_task(request, pk):
    task = get_object_or_404(Task, pk=pk, user=request.user)
    task.delete()
    response = HttpResponse(status=204)
    response['HX-Trigger'] = 'delete-task'
    return response

# def follow_user(request, user_id):
#     user_to_follow = get_object_or_404(User, id=user_id)
#     is_following = request.user.following.filter(id=user_id).exists()
#     if not is_following:
#         Follow.objects.create(follower=request.user, following=user_to_follow)
#     return redirect('profile', is_following=is_following)  # Pass the following status


# def unfollow_user(request, user_id):
#     user_to_unfollow = get_object_or_404(User, id=user_id)
#     request.user.following.filter(id=user_id).delete()
#     return redirect('profile')


 

templates/core/partials/questions.html
 <div class="flex border-b gap-4 justify-around p-4 items-start bg-gray-50">
                    <div class="flex flex-col gap-3 text-right">
                        <span class="text-xs">O votes</span>
                        <span class="text-xs">O answers</span>
                        <span class="text-xs">20 views</span>
                    </div>
                  <div class="max-w-[80%] space-y-4">
                        <a href="{% url 'questionflow:question-detail' question.pk %}" class="text-blue-500 font-semibold">{{question.content}}!</a>
                        <div class="flex items-center justify-between"> 
                            <div class="flex gap-3">
                                {% for tag in question.tags.all %}
                                <a href="{% url 'questionflow:tagger' tag.slug %}" class="py-1 px-2 bg-gray-200 hover:bg-gray-100 text-xs">{{tag}}</a>
                                {% endfor %}
                                </div>

                            <div class="flex gap-2 items-center">
                                <a href="#" class="flex gap-1 items-center hover:underline text-sm"><img src="{{question.user.profile.profileImage.url}}" class="w-4 h-4 md:w-5 md:h-5 rounded-md" alt=""> <span>@{{question.user.username}}</span></a>
                                <span class="text-xs">modified {{question.created_at|timesince}}</span>
                            </div>
                        </div>
                    </div>
                </div>

templates/core/partials/tasks.html
 {% load widget_tweaks %}

 {% load partials %}
 
 <div class="space-y-5 mt-5 rounded-lg" id="todo-body">
        {% if filter.qs %}
        {% for task in filter.qs %}
         {% partialdef taskitem-partial inline=True %}
            <div class="flex items-center justify-between py-2 px-6 shadow-lg bg-gradient-to-r hover:shadow-xl duration-100 from-slate-100 to-slate-300 ">
                <div class="space-x-4 flex flex-col items-start">
                    <div>
                        <p class="font-bold text-md md:text-xl">{{task.title}}</p>
                        <span>{{task.description}}</span>
                    </div>
                    <div>
                        <span class="text-sm">
                            <i class="fa-regular fa-clock"></i>
                            {{task.created_at|timesince}}
                        </span>
                    </div>
                </div>
                {% partialdef taskcomplete-partial inline=True %}
                <article class="flex items-center ps-4 space-x-5">
                    <button
                    hx-post="{% url 'complete-task' task.pk %}"
                    hx-target="closest article"
                    hx-swap="outerHTML"
                    >
                    <div>
                        {% if task.is_completed == True %}
                       <i class="fa-solid fa-square-check"></i>
                       <label for="bordered-checkbox-2" class="w-full py-4 ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">Task Completed</label>
                       {% else %}
                       <i class="fa-regular fa-square-check"></i>
                       <label for="bordered-checkbox-2" class="w-full py-4 ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">Not Completed</label>
                       {% endif %}

                    </div>
                    </button>
                    <button
                    hx-delete="{% url 'delete-task' task.pk %}"
                    hx-on:delete-task="this.closest('div').remove()"
                    class="bg-slate-100 hover:bg-slate-200 p-2 rounded-full flex items-center justify-center">
                        <i class="fa-solid fa-trash"></i>
                    </button>
                </article>
                {% endpartialdef %}
            </div>
            {% endpartialdef %}
            {% endfor %}

            {% else %}

            <h2 class="font-bold">You dont have any Task List Click on the Add Task Button to create One.</h2>

            {% endif %}
   </div>